context:
  name: posting
  version: "2.4.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7784cc49eaeed3ea78252ad4fff20db49284aa1e29a33ed21ed4920bfdbf58c4
  patches:
    - change-xdg-package-name.patch

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0
  python:
    entry_points:
      - posting = posting.__main__:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - click >=8.1.7,<9.0.0
    - xdg >=6.0.0,<7.0.0
    - click-default-group >=1.2.4,<2.0.0
    - httpx >=0.27.2,<1.0.0
    - pyperclip >=1.9.0,<2.0.0
    - pydantic >=2.9.2,<3.0.0
    - pyyaml >=6.0.2,<7.0.0
    - pydantic-settings >=2.4.0,<3.0.0
    - python-dotenv >=1.0.1,<2.0.0
    - textual ==2.1.1
    - textual-autocomplete ==4.0.0a0
    - watchfiles >=0.24.0

tests:
  - script:
      - posting --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://posting.sh/
  summary: 'A powerful HTTP client that lives in your terminal.'
  description: |
    Posting is an HTTP client, not unlike Postman and Insomnia.
    As a TUI application, it can be used over SSH and enables efficient keyboard-centric workflows.
    Your requests are stored locally in simple YAML files, so they're easy to read and version control.
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/darrenburns/posting
  documentation: https://posting.sh/guide/

extra:
  recipe-maintainers:
    - claudiushaag
